# Generated by Django 4.2.4 on 2023-09-05 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_professor_email_professor_identification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
