# Generated by Django 4.2.4 on 2023-09-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_course_uuid_grade_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'grade', 'verbose_name_plural': 'grades'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'professor', 'verbose_name_plural': 'professors'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
