# Generated by Django 4.2.4 on 2023-09-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_alter_course_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='grades.student'),
        ),
    ]
