# Generated by Django 4.2.4 on 2023-09-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='grades.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_enrolled',
            field=models.ManyToManyField(blank=True, to='grades.course'),
        ),
    ]
