# Generated by Django 4.2.4 on 2023-09-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0010_alter_course_students_alter_student_courses_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='professor',
            name='role',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
