# Generated by Django 4.2.4 on 2023-09-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0011_remove_professor_password_remove_student_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='professor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='name',
        ),
    ]
