# Generated by Django 4.2.4 on 2023-09-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0012_rename_professor_name_professor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
