# Generated by Django 4.2.4 on 2023-09-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0015_alter_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ends',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='starts',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
