# Generated by Django 4.2.4 on 2023-09-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0017_rename_time_schedule_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ends',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='starts',
            field=models.TimeField(default='00:00'),
        ),
    ]
