# Generated by Django 4.2.4 on 2023-09-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0018_alter_schedule_duration_alter_schedule_ends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='ends',
            field=models.TimeField(default='00:00', unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='starts',
            field=models.TimeField(default='00:00', unique=True),
        ),
    ]
