# Generated by Django 4.2.4 on 2023-09-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0020_alter_schedule_ends_alter_schedule_starts'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
